### ISSUE TITLE
Functionality to validate plugin metadata

### ISSUE THREAD

**Issue by tcorbettclark** [Encapsia/encapsia-api#23]
Moves from https://github.com/tcorbettclark/encapsia-cli/issues/18

**Comment by petrem** [comment]
A plugin's metadata (plugin.toml) needs to obey a few rules and has a well defined structure:

General rules
===========

   * Must be a valid TOML file.
   * All top-level keys marked as mandatory must be included in a manifest.
   * In optional tables, keys marked as mandatory must be included if the table is present.
   * Other keys or tables must not be present.
   * Where given, values must obey restrictions (e.g. type, range etc).

Top-level keys
===========

| Key | Value type and restrictions | Status |
| -- | -- | -- |
| name | String: Latin lowercase letters and underscore. Cannot start with "pg_". In other words, should match `r"^(?!pg_)[a-z][a-z0-9_]*$", re.ASCII)`. Cannot be any of: "analytics core operational pluginsmanager public reporting uploads v1 dbctl documentation fixture_manager tmp"| mandatory |
| description | String | mandatory |
| version | String | mandatory |
| created_by | String | mandatory |
| reset_on_install| Boolean | OPTIONAL |
| created_at | String: ISO8601 datetime | OPTIONAL |
| n_task_workers | Integer: positive or zero. Should probably be limited to a maximum value. | OPTIONAL |
| post_install_task | String: should be a valid/existing/defined task in this plugin. | OPTIONAL |
| pre_uninstall_task | String: should be a valid/existing/defined task in this plugin. | OPTIONAL |
| tags | Array of String. Each tag should only contain `[A-Za-z0-9_-]`. | OPTIONAL |

Tags should be: webapp, insights-gallery, middleware, `variant-.*`. Hyphens should be preferred to underscores, but I don't think that must be a rule.

Example:
```
name = "monkey_king"
description = "Greate Sage, Equal of Heaven plugin"
version = "0.0.1"
created_by = "someone@example.org"
n_task_workers = 1
reset_on_install = true
post_install_task = "randomness.seed"
tags = ["example", "chaos-monkey", "great-sage"]
```

Tables
=====

System users table
----------------------------

Name: `system_users`
Syntax: https://toml.io/en/v1.0.0#array-of-tables
Status: optional

| Key | Type and restrictions | Status |
| -- | -- | -- |
| `system_users.[].name` | String: Latin lowercase letters and underscore. | mandatory |
| `system_users.[].capabilities` | Array of String | mandatory |

Example:

```
[[system_users]]
name = "descriptive_name"
capabilities = ["capa1", "capa2"]

[[system_users]]
name = "another_descriptive_name"
capabilities = ["kappa.kappa.wong", "hyperuser"]
```

Permissions
------------------

TODO

Views and Tasks Public API
---------------------------------------

TODO

Webapp Table
---------------------

TODO

Only when "webapp" tag is present, when it becomes mandatory.

Insights-Gallery Table
-------------------------------

TODO

Only when "insights-gallery" tag is present, when it becomes mandatory.

Strict and non-strict checks
======================
We may have mandatory and optional checks (strict or non-strict, if you prefer). For example, the list of acceptable tags may vary, and while we can update the checks, adopting new versions of this package may be slow -- in such cases the client may opt for non-strict checks that would not verify tags validity. Others, (e.g. encapsia-cli's plugins dev-build) could benefit from stricter checks. This would allow using non-strict checks where it would be more difficult.
